// Polish
// Auto-generated by scripts/translate-i18n.mjs

export const pl = {
  "layout": {
    "metadata": {
      "title": "InfiPlot",
      "description": "InfiPlot"
    }
  },
  "home": {
    "examples": {
      "male": [],
      "female": [],
      "x": []
    },
    "options": {
      "gender": "",
      "artStyle": "",
      "plotStyle": "",
      "voice": "",
      "pacing": ""
    },
    "genders": {
      "male": "",
      "female": "",
      "x": ""
    },
    "artStyles": {},
    "plotStyles": {
      "straightforward": "",
      "twist": ""
    },
    "voiceOptions": {
      "off": "",
      "on": ""
    },
    "pacings": {
      "fast": "",
      "relaxed": ""
    },
    "stories": {},
    "ui": {
      "start": "",
      "loadStory": "",
      "settings": "",
      "searchPlaceholder": "",
      "noMatchingStyle": "",
      "close": "",
      "back": "",
      "save": "",
      "cancel": "",
      "saveAndSelect": ""
    },
    "styleModal": {},
    "hero": {
      "title": "",
      "placeholder": " ",
      "enterHint": ""
    },
    "hint": {
      "text": (params: { authEnabled?: boolean }) => {
            const authHint = params.authEnabled ? ' (wymagane logowanie podczas beta, darmowa gra)' : '';
            return `Wprowadź swoje pomysły, skonfiguruj style i kliknij "Rozpocznij", aby zagrać${authHint}. Możesz także wybrać kuratorską historię z dołu, aby szybko doświadczyć <em>InfiPlot</em>. Kliknij "Ustawienia", aby wprowadzić swoje imię i skonfigurować własne klucze tekstu, obrazu, widoku i TTS—wszystko przechowywane lokalnie w twojej przeglądarce dla bardziej stabilnego doświadczenia.`;
          },
      "closeAriaLabel": "Nie pokazuj więcej tej podpowiedzi"
    },
    "about": {},
    "errors": {
      "emptyFile": "",
      "fileTooLarge": "",
      "unpackFailed": "",
      "parseFailed": "",
      "cardNotFound": ""
    }
  },
  "play": {},
  "settings": {},
  "auth": {},
  "history": {},
  "customForm": {},
  "language": {
    "title": "",
    "current": "",
    "select": ""
  }
} as const;

export type PlTranslations = typeof pl;
