// Portuguese (Brazil)
// Auto-generated by scripts/translate-i18n.mjs

export const ptBR = {
  "layout": {
    "metadata": {
      "title": "InfiPlot",
      "description": "InfiPlot"
    }
  },
  "home": {
    "examples": {
      "male": [],
      "female": [],
      "x": []
    },
    "options": {
      "gender": "",
      "artStyle": "",
      "plotStyle": "",
      "voice": "",
      "pacing": ""
    },
    "genders": {
      "male": "",
      "female": "",
      "x": ""
    },
    "artStyles": {},
    "plotStyles": {
      "straightforward": "",
      "twist": ""
    },
    "voiceOptions": {
      "off": "",
      "on": ""
    },
    "pacings": {
      "fast": "",
      "relaxed": ""
    },
    "stories": {},
    "ui": {
      "start": "",
      "loadStory": "",
      "settings": "",
      "searchPlaceholder": "",
      "noMatchingStyle": "",
      "close": "",
      "back": "",
      "save": "",
      "cancel": "",
      "saveAndSelect": ""
    },
    "styleModal": {},
    "hero": {
      "title": "",
      "placeholder": " ",
      "enterHint": ""
    },
    "hint": {
      "text": (params: { authEnabled?: boolean }) => {
            const authHint = params.authEnabled ? ' (login necessário durante o beta, grátis para jogar)' : '';
            return `Digite suas ideias, configure estilos e clique em "Iniciar" para jogar${authHint}. Você também pode escolher uma história curada abaixo para experimentar rapidamente <em>InfiPlot</em>. Clique em "Configurações" para inserir seu nome e configurar suas próprias chaves de texto, imagem, visão e TTS—tudo armazenado localmente no seu navegador para uma experiência mais estável.`;
          },
      "closeAriaLabel": "Não mostrar mais este aviso"
    },
    "about": {},
    "errors": {
      "emptyFile": "",
      "fileTooLarge": "",
      "unpackFailed": "",
      "parseFailed": "",
      "cardNotFound": ""
    }
  },
  "play": {},
  "settings": {},
  "auth": {},
  "history": {},
  "customForm": {},
  "language": {
    "title": "",
    "current": "",
    "select": ""
  }
} as const;

export type PtBRTranslations = typeof ptBR;
