// Ukrainian
// Auto-generated by scripts/translate-i18n.mjs

export const uk = {
  "layout": {
    "metadata": {
      "title": "InfiPlot",
      "description": "InfiPlot"
    }
  },
  "home": {
    "examples": {
      "male": [],
      "female": [],
      "x": []
    },
    "options": {
      "gender": "",
      "artStyle": "",
      "plotStyle": "",
      "voice": "",
      "pacing": ""
    },
    "genders": {
      "male": "",
      "female": "",
      "x": ""
    },
    "artStyles": {},
    "plotStyles": {
      "straightforward": "",
      "twist": ""
    },
    "voiceOptions": {
      "off": "",
      "on": ""
    },
    "pacings": {
      "fast": "",
      "relaxed": ""
    },
    "stories": {},
    "ui": {
      "start": "",
      "loadStory": "",
      "settings": "",
      "searchPlaceholder": "",
      "noMatchingStyle": "",
      "close": "",
      "back": "",
      "save": "",
      "cancel": "",
      "saveAndSelect": ""
    },
    "styleModal": {},
    "hero": {
      "title": "",
      "placeholder": " ",
      "enterHint": ""
    },
    "hint": {
      "text": (params: { authEnabled?: boolean }) => {
            const authHint = params.authEnabled ? ' (вхід потрібен під час бета-тестування, безкоштовна гра)' : '';
            return `Введіть свої ідеї, налаштуйте стилі та натисніть "Почати" для гри${authHint}. Ви також можете обрати вибрану історію знизу, щоб швидко випробувати <em>InfiPlot</em>. Натисніть "Налаштування", щоб ввести своє ім'я та налаштувати власні ключі тексту, зображення, зору та TTS—все зберігається локально у вашому браузері для стабільнішого досвіду.`;
          },
      "closeAriaLabel": "Більше не показувати цю підказку"
    },
    "about": {},
    "errors": {
      "emptyFile": "",
      "fileTooLarge": "",
      "unpackFailed": "",
      "parseFailed": "",
      "cardNotFound": ""
    }
  },
  "play": {},
  "settings": {},
  "auth": {},
  "history": {},
  "customForm": {},
  "language": {
    "title": "",
    "current": "",
    "select": ""
  }
} as const;

export type UkTranslations = typeof uk;
